### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by colinrymer** [knewter/elixir_friends#7]
I just opened a PR, but without a `CONTRIBUTING.md` I'm not sure what the proper process is for making it as easy as possible for the maintainer(s) to merge my code.

**Comment by knewter** [comment]
We should definitely add one, but until now haven't had contributions so wasn't sure myself :)  This process is good, and I'll try to remember to add a CONTRIBUTING.md in the future.  Is there a good one you can point to that I could review and crib?  I don't really know what people look for in one, though I use them any time there is one :)

**Comment by colinrymer** [comment]
https://github.com/thoughtbot/factory_girl_rails/blob/master/CONTRIBUTING.md and https://github.com/thoughtbot/suspenders/blob/master/CONTRIBUTING.md are two good examples.

https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md is a good (and thorough) one.

**Comment by knewter** [comment]
I just added one, thanks for the suggestion :)  I'm sure it'll be iterated on over time (I hope)

**Comment by colinrymer** [comment]
Sweet! Thanks!
